### ISSUE TITLE
Running `cargo make serve` on Windows fails

### ISSUE THREAD

**Issue by rgripper** [NiklasEi/bevy_game_template#7] opened 2021-04-21 08:01 UTC
I've forked your template and trying to run on web 'as-is'. It finishes compilation and then unfortunately fails with this:

```
   ...
   Replacing C:\Users\username\.cargo\bin\wasm2es6js.exe
    Replaced package `wasm-bindgen-cli v0.2.69` with `wasm-bindgen-cli v0.2.69` (executables `wasm-bindgen-test-runner.exe`, `wasm-bindgen.exe`, 
`wasm2es6js.exe`)
[cargo-make] INFO - Execute Command: "wasm-bindgen" "--out-dir" "target/wasm32-unknown-unknown/release/" "--out-name" "wasm" "--target" "web" "--no-typescript" "target/wasm32-unknown-unknown/release/bevy_game.wasm"
[cargo-make] INFO - Execute Command: "mkdir" "-p" "build/web/target"
[cargo-make] ERROR - Error while executing command, error: Os {
    code: 2,
    kind: NotFound,
    message: "The system cannot find the file specified.",
}
```

I think it's something trivial, but I can't figure it out.

**Comment by NiklasEi** [comment] 2021-04-21 21:01
Hey, thanks for raising the issue.
I am currently settign up my windows PC to be able to test this myself, but it looks like the `mkdir` command just needs to be different for Windows.

**Comment by rgripper** [comment] 2021-04-21 21:21
I tried to run the command separately and it didn't complain. Thanks for helping out!

**Comment by NiklasEi** [comment] 2021-04-23 05:57
I finally finished setting up my Windows machine. In my case the command worked out of the box. I have very little experience with commands on Windows, so I am not sure how to change it to be more compatible.

> I tried to run the command separately and it didn't complain.
Do you mean you ran the `mkdir` command as is outside of the `cargo-make` task? Or did you run several `mkdir` commands always just creating one subdirectory?

**Comment by rgripper** [comment] 2021-04-23 06:39
I ran it outside of the scripts 😀   I'll do a clean download of your template and try everything again.

**Comment by rgripper** [comment] 2021-04-23 19:35
Nah, same thing. How would you suggest to debug this 🧐 ? Quite annoying to wait for a whole minute for everything to compile just to get this error.

**Comment by NiklasEi** [comment] 2021-04-27 19:43
This seems to be a simple issue, but to be honest I have no idea what `mkdir` on windows actually does/can do. Seems that there are a lot of possible different setups here (actually "works on my Win10 machine" ^^).
Maybe you could try some small changes like `build/web/target` -> `./build/web/target`? I don't think you need to do a clean download of the template every time. Just make sure to not have the `build/web` directory, then the situation should be the same as for a fresh download.

**Comment by will-hart** [comment] 2021-05-02 08:18
Same error for me on Win10 running Windows Terminal/Powershell/Starship prompt. I've tried

```toml
[tasks.create-build-dir]
args = ["./build/web/target"]
command = "mkdir"
```

and 

```toml
[tasks.create-build-dir]
args = ["-p", "./build/web/target"]
command = "mkdir"
```

Running either `mkdir` command directly from the command line in the project root creates the folders as expected.

**Comment by rgripper** [comment] 2021-05-02 18:51
Hey @NiklasEi, I emailed you recently, not sure if you mind.

**Comment by NiklasEi** [comment] 2021-05-02 19:44
> This works though
> 
> ```toml
> [tasks.create-build-dir]
> script_runner = "@duckscript"
> script = [
> '''
> p = canonicalize "build/web/target"
> mkdir ${p}
> ''']
> ```
I tested this and for me, it also works. I will push this and maybe @rgripper can very, that this also solves the issue on his machine?

**Comment by will-hart** [comment] 2021-05-02 21:40
It seems there are some weird path things on windows. I had to replace all the `cp` and `mv` commands with this before it worked.

```toml

[tasks.copy-files-for-release]
script_runner = "@duckscript"
script = [
'''
target = set "./build/web/target"
web = set "./build/web"
windows = set "./build/windows"

echo "Creating ${target}"
rm -r ${web}
mkdir ${target}

echo "Copying ${windows}/icon.ico to ${web}/icon.ico"
cp ${windows}/icon.ico ${web}/icon.ico
echo "Moving ${web}/icon.ico to ${web}/favicon.ico"
mv ${web}/icon.ico ${web}/favicon.ico

echo "Copying ${TARGET_DIR}${CARGO_MAKE_CRATE_NAME}.wasm to ${target}"
cp ${TARGET_DIR}${CARGO_MAKE_CRATE_NAME}.wasm ${target}/${CARGO_MAKE_CRATE_NAME}.wasm

echo "Copying ${TARGET_DIR}wasm.js to ${target}"
cp ${TARGET_DIR}wasm.js ${target}/wasm.js

echo "Copying ${TARGET_DIR}wasm_bg.wasm to ${target}"
cp ${TARGET_DIR}wasm_bg.wasm ${target}/wasm_bg.wasm

echo "Copying ./index.html to ${web}"
cp ./index.html ${web}/index.html

echo "Copying ./assets to ${web}"
cp ./assets ${web}

echo "Copying ./credits to ${web}"
cp ./credits ${web}
''']

```

**Comment by sagiegurari** [comment] 2021-05-03 06:29
don't have windows myself, but this is a strange one.
a task with a command + args is basically like running rust std::process::Command which i probably behaves differently than running the command inside a shell.
however, the question is this running inside a linux subsystem?
because i see an example of:
```toml
[tasks.create-build-dir]
args = ["-p", "${CARGO_MAKE_WORKING_DIRECTORY}/build/web/target"]
command = "mkdir"
dependencies = ["echo-path"]
```
and i'm not sure dos knows what -p is (could be wrong).

**Comment by MikulasZelinka** [comment] 2021-05-05 23:28
I can confirm that the issue appears in all `cp`, `mv` and `mkdir` commands on Windows when run from `cargo make serve`.

- However, all of the commands (except for mkdir's `-p`) work when executed manually outside the `make`.
- The workaround https://github.com/NiklasEi/bevy_game_template/issues/7#issuecomment-830876426 solves the issue.

**Comment by NiklasEi** [comment] 2021-05-09 07:01
@MikulasZelinka Thanks for testing and reporting your findings!

@will-hart would you be willing to open a PR to close this issue with your changes above?

**Comment by will-hart** [comment] 2021-05-11 21:20
Hey sorry, been busy with IRL. I can create a PR, although I can't test on MacOS or Linux.

**Comment by sagiegurari** [comment] 2021-05-12 05:29
i suddenly remembered something about mkdir on windows.... the reason you cant run commands like mkdir on windows, is because its an internal cmd command and not a standalone executable.
meaning, it only works when inside a windows shell environment.

duckscript is indeed the way to go forward since it provides a real cross platform api.

**Comment by NiklasEi** [comment] 2021-05-15 13:33
Resolved using the script @will-hart proposed

**Closed by NiklasEi** 2021-05-15 13:33 UTC

**Comment by MikulasZelinka** [comment] 2021-05-17 09:21
Link to the relevant PR: #10.
